baseURL = "https://finanzas.rodomar.mx/"
languageCode = "en-us"
defaultContentLanguage = "es"
title = "Blog"
theme = "LoveIt"
enableEmoji = true
enableGitInfo = true

[languages]
  [languages.en]
    weight = 1
    # language code
    languageCode = "en"
    # website title
    title = "Blog"
    # language name
    languageName = "English"
    # whether to include Chinese/Japanese/Korean
    hasCJKLanguage = false
    # default amount of posts in each pages
    paginate = 12
    # [UA-XXXXXXXX-X] google analytics code
    googleAnalytics = "UA-119169351-2"
    # copyright description used only for seo schema
    copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
    # date format
    dateFormatToUse = "2006-01-02"
    # Menu Info
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "posts"
        # you can add extra information before the name (HTML format is allowed), such as icons
        pre = ""
        name = "Posts"
        url = "/posts/"
        # title will be shown when you hover on this menu link.
        title = ""
        weight = 1
      [[languages.en.menu.main]]
        identifier = "tags"
        pre = ""
        name = "Tags"
        url = "/tags/"
        title = ""
        weight = 2
      [[languages.en.menu.main]]
        identifier = "categories"
        pre = ""
        name = "Categories"
        url = "/categories/"
        title = ""
        weight = 3
      [[languages.en.menu.main]]
        identifier = "about"
        pre = ""
        name = "About me"
        url = "/about/"
        title = ""
        weight = 5
      [[languages.en.menu.main]]
        identifier = "github"
        pre = "<i class='fab fa-github fa-fw'></i>"
        name = ""
        url = "https://github.com/ramrodo/blog-finanzas-rodomar-mx/"
        title = "GitHub"
        weight = 6
      [languages.en.params]
        # site description
        description = "About LoveIt Theme"
        # site keywords
        keywords = ["Theme", "Hugo"]
        # site default theme ("light", "dark", "auto")
        defaultTheme = "auto"
        # Home Page Info
        [languages.en.params.home]
          # Home Page Profile
          [languages.en.params.home.profile]
            enable = true
            # Gravatar Email for preferred avatar in home page
            gravatarEmail = "rodomar@outlook.com"
            # URL of avatar shown in home page
            avatarURL = "/images/selfie.jpg"
            # subtitle shown in home page
            subtitle = "Rodolfo Martínez Vega"
            # whether to use typeit animation for subtitle
            typeit = true
            # whether to show social links
            social = true
          # Home Page Posts
          [languages.en.params.home.posts]
            enable = true
            # special amount of posts in each home posts page
            paginate = 6
            # default behavior when you don't set "hiddenFromHomePage" in front matter
            defaultHiddenFromHomePage = false
        # Social Info in home page
        [languages.en.params.social]
          Twitter = "ramrodo"
          Email = "rodomar@outlook.com"
          Goodreads = "92717248-rodolfo-mart-nez"
          RSS = true
          # [languages.en.params.social.Mastodon]
            # id = "@xxxx"
            # prefix = "https://mastodon.technology/"
        # Social Share Links in post page
        [languages.en.params.share]
          enable = true
          Twitter = true
          Facebook = true
          Linkedin = true
          Whatsapp = true
          Pinterest = true
          # Tumblr = true
          HackerNews = true
          # Reddit = true
          # VK = true
          # Buffer = true
          # Xing = true
          # Line = true
          # Instapaper = true
          # Pocket = true
          # Digg = true
          # Stumbleupon = true
          # Flipboard = true
          # Weibo = true
          # Renren = true
          # Myspace = true
          # Blogger = true
          # Baidu = true
          # Odnoklassniki = true
          # Evernote = true
          # Skype = true
          # Trello = true
          # Mix = true
        # Comment Config
        [languages.en.params.comment]
          enable = true
          # Disqus Comment Config (https://disqus.com/)
          [languages.en.params.comment.disqus]
            # Disqus shortname to use Disqus in posts
            shortname = ""
          # Gitalk Comment Config (https://github.com/gitalk/gitalk)
          [languages.en.params.comment.gitalk]
            owner = ""
            repo = ""
            clientId = ""
            clientSecret = ""
          # Valine Comment Config (https://github.com/xCss/Valine)
          [languages.en.params.comment.valine]
            enable = false
            appId = "U23b5sRThXjP8EP6oVBC6m1O-MdYXbMMI"
            appKey = "bRc23QOo1E6FOOBsRvbUwws1"
            placeholder = "Your comment ..."
            notify = false
            verify = true
            avatar = "mp"
            meta= ""
            pageSize = 10
            lang = "en"
            visitor = true
            recordIP = true
          # Facebook Comment Config (https://developers.facebook.com/docs/plugins/comments)
          [languages.en.params.comment.facebook]
            enable = true
            width = "100%"
            numPosts = 10
            appId = "239685623897243"
            languageCode = "es_MX"

  [languages.es]
    weight = 1
    # language code
    languageCode = "es"
    # website title
    title = "Blog"
    # language name
    languageName = "Español"
    # whether to include Chinese/Japanese/Korean
    hasCJKLanguage = false
    # default amount of posts in each pages
    paginate = 12
    # [UA-XXXXXXXX-X] google analytics code
    googleAnalytics = "UA-119169351-2"
    # copyright description used only for seo schema
    copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
    # date format
    dateFormatToUse = "2006-01-02"
    # Menu Info
    [languages.es.menu]
      [[languages.es.menu.main]]
        identifier = "posts"
        # you can add extra information before the name (HTML format is allowed), such as icons
        pre = ""
        name = "Artículos"
        url = "/posts/"
        # title will be shown when you hover on this menu link.
        title = ""
        weight = 1
      [[languages.es.menu.main]]
        identifier = "tags"
        pre = ""
        name = "Etiquetas"
        url = "/tags/"
        title = ""
        weight = 2
      [[languages.es.menu.main]]
        identifier = "categories"
        pre = ""
        name = "Categorías"
        url = "/categories/"
        title = ""
        weight = 3
      [[languages.es.menu.main]]
        identifier = "about"
        pre = ""
        name = "Acerca de mí"
        url = "/about/"
        title = ""
        weight = 5
      [[languages.es.menu.main]]
        identifier = "github"
        pre = "<i class='fab fa-github fa-fw'></i>"
        name = ""
        url = "https://github.com/ramrodo/blog-finanzas-rodomar-mx/"
        title = "GitHub"
        weight = 6
      [languages.es.params]
        # site description
        description = "About LoveIt Theme"
        # site keywords
        keywords = ["Theme", "Hugo"]
        # site default theme ("light", "dark", "auto")
        defaultTheme = "auto"
        # Home Page Info
        [languages.es.params.home]
          # Home Page Profile
          [languages.es.params.home.profile]
            enable = true
            # Gravatar Email for preferred avatar in home page
            gravatarEmail = "rodomar@outlook.com"
            # URL of avatar shown in home page
            avatarURL = "/images/selfie.jpg"
            # subtitle shown in home page
            subtitle = "Rodolfo Martínez Vega"
            # whether to use typeit animation for subtitle
            typeit = true
            # whether to show social links
            social = true
          # Home Page Posts
          [languages.es.params.home.posts]
            enable = true
            # special amount of posts in each home posts page
            paginate = 6
            # default behavior when you don't set "hiddenFromHomePage" in front matter
            defaultHiddenFromHomePage = false
        # Social Info in home page
        [languages.es.params.social]
          Twitter = "ramrodo"
          Email = "rodomar@outlook.com"
          Goodreads = "92717248-rodolfo-mart-nez"
          RSS = true
          # [languages.es.params.social.Mastodon]
            # id = "@xxxx"
            # prefix = "https://mastodon.technology/"
        # Social Share Links in post page
        [languages.es.params.share]
          enable = true
          Twitter = true
          Facebook = true
          Linkedin = true
          Whatsapp = true
          Pinterest = true
          # Tumblr = true
          HackerNews = true
          # Reddit = true
          # VK = true
          # Buffer = true
          # Xing = true
          # Line = true
          # Instapaper = true
          # Pocket = true
          # Digg = true
          # Stumbleupon = true
          # Flipboard = true
          # Weibo = true
          # Renren = true
          # Myspace = true
          # Blogger = true
          # Baidu = true
          # Odnoklassniki = true
          # Evernote = true
          # Skype = true
          # Trello = true
          # Mix = true
        # Comment Config
        [languages.es.params.comment]
          enable = true
          # Disqus Comment Config (https://disqus.com/)
          [languages.es.params.comment.disqus]
            # Disqus shortname to use Disqus in posts
            shortname = ""
          # Gitalk Comment Config (https://github.com/gitalk/gitalk)
          [languages.es.params.comment.gitalk]
            owner = ""
            repo = ""
            clientId = ""
            clientSecret = ""
          # Valine Comment Config (https://github.com/xCss/Valine)
          [languages.es.params.comment.valine]
            enable = false
            appId = "U23b5sRThXjP8EP6oVBC6m1O-MdYXbMMI"
            appKey = "bRc23QOo1E6FOOBsRvbUwws1"
            placeholder = "Your comment ..."
            notify = false
            verify = false
            avatar = "mp"
            meta= ""
            pageSize = 10
            lang = "en"
            visitor = true
            recordIP = true
          # Facebook Comment Config (https://developers.facebook.com/docs/plugins/comments)
          [languages.es.params.comment.facebook]
            enable = true
            width = "100%"
            numPosts = 10
            appId = "239685623897243"
            languageCode = "es_MX"

[params]
  version = "0.2.X"
  gitRepo = "https://github.com/ramrodo/blog-finanzas-rodomar-mx/"
  # Header info
  [params.header]
    # desktop header mode ("fixed", "normal", "auto")
    desktopMode = "fixed"
    # mobile header mode ("fixed", "normal", "auto")
    mobileMode = "auto"
  # Footer Copyright Info
  [params.footer]
    # Site creation time
    since = 2020
    # ICP info only in China (HTML format is allowed)
    icp = ""
    # license info (HTML format is allowed)
    license= '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
  # Page config
  [params.page]
    # whether to use lightgallery in the page
    lightgallery = true
    # whether to show link to Raw Markdown content of the post
    linkToMarkdown = true
  # mathematical formulas (KaTeX https://katex.org/)
  [params.math]
    enable = true
    # default block delimiter is $$ ... $$ and \\[ ... \\]
    blockLeftDelimiter = ""
    blockRightDelimiter = ""
    # default inline delimiter is $ ... $ and \\( ... \\)
    inlineLeftDelimiter = ""
    inlineRightDelimiter = ""
    # KaTeX extension copy_tex
    copyTex = true
    # KaTeX extension mhchem
    mhchem = true
  # Social Share Links in post page
  [params.share]
    enable = true
    Twitter = true
    Facebook = true
    Linkedin = true
    Whatsapp = true
    Pinterest = true
    # Tumblr = true
    HackerNews = true
    # Reddit = true
    # VK = true
    # Buffer = true
    # Xing = true
    # Line = true
    # Instapaper = true
    # Pocket = true
    # Digg = true
    # Stumbleupon = true
    # Flipboard = true
    # Weibo = true
    # Renren = true
    # Myspace = true
    # Blogger = true
    # Baidu = true
    # Odnoklassniki = true
    # Evernote = true
    # Skype = true
    # Trello = true
    # Mix = true
  # Comment Config
  [params.comment]
    enable = true
    # Disqus Comment Config (https://disqus.com/)
    [params.comment.disqus]
      # LoveIt   v0.1.1
      enable = false
      # Disqus shortname to use Disqus in posts
      shortname = ""
    # Gitalk Comment Config (https://github.com/gitalk/gitalk)
    [params.comment.gitalk]
      # LoveIt   v0.1.1
      enable = false
      owner = ""
      repo = ""
      clientId = ""
      clientSecret = ""
    # Valine Comment Config (https://github.com/xCss/Valine)
    [params.comment.valine]
      enable = false
      appId = "U23b5sRThXjP8EP6oVBC6m1O-MdYXbMMI"
      appKey = "bRc23QOo1E6FOOBsRvbUwws1"
      placeholder = "Your comment ..."
      notify = false
      verify = false
      avatar = "mp"
      meta= ""
      pageSize = 10
      lang = "en"
      visitor = true
      recordIP = true
    # Facebook Comment Config (https://developers.facebook.com/docs/plugins/comments)
    [params.comment.facebook]
      enable = true
      width = "100%"
      numPosts = 10
      appId = "239685623897243"
      languageCode = "es_MX"

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    style = "monokai"
    tabWidth = 4
  # Goldmark is from Hugo 0.60 the default library used for Markdown
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      # whether to use HTML tags directly in the document
      unsafe = true
  # Table Of Contents settings
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

# Author Info
[author]
  name = "xxxx"
  link = ""

# Sitemap Info
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

# Permalinks Info (https://gohugo.io/content-management/urls/#permalinks)
[Permalinks]
  # posts = ":year/:month/:filename"
  posts = ":filename"

# Privacy Info (https://gohugo.io/about/hugo-and-gdpr/)
[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true

  [privacy.youtube]
    privacyEnhanced = true

# Options to make output .md files
[mediaTypes]
  [mediaTypes."text/plain"]
    suffixes = ["md"]

# Options to make output .md files
[outputFormats.MarkDown]
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false

# Options to make hugo output files
[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]
